### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by feijunbo** [ShusenWang/NAACL2022-RCL#1]

**Comment by ShusenWang** [comment]
We've been very busy lately，and the code will be released in September.

**Comment by feijunbo** [comment]
Hi, if you are too busy to release the code, could you tell me the details of the training and validation on SemEval2010 Task8?

**Comment by feijunbo** [comment]
> We've been very busy lately，and the code will be released in September.

Hi, if you are too busy to release the code, could you tell me the details of the training and validation on SemEval2010 Task8?

**Comment by ShusenWang** [comment]
The code has been released in the repo.
